version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1
      - . $HOME/.asdf/asdf.sh
      - asdf plugin add flutter
      - asdf install
      - asdf reshim
  build:
    commands:
      - flutter pub get
      - flutter build web
